/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author W8
 */
public class NewJFrame extends javax.swing.JFrame {
    String jns="";
    int jml;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        panel.setVisible(false);
        getJumlah();
        setJenis();
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            b1.setVisible(false);
            b2.setVisible(false);
            bil1.setVisible(false);
            bil2.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jmlBil = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tHasil = new javax.swing.JTextArea();
        ket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 120, 30);

        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 50, 100, 20);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih salah satu--", "Perkalian", "Pembagian", "Penjumlahan", "Pengurangan" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(260, 50, 150, 30);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        panel.setBackground(new java.awt.Color(204, 204, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setLayout(null);

        jmlBil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jmlBil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlBilActionPerformed(evt);
            }
        });
        panel.add(jmlBil);
        jmlBil.setBounds(190, 50, 110, 30);
        panel.add(b1);
        b1.setBounds(190, 80, 150, 30);
        panel.add(b2);
        b2.setBounds(190, 120, 150, 30);
        panel.add(b3);
        b3.setBounds(190, 160, 150, 30);
        panel.add(b4);
        b4.setBounds(190, 200, 150, 30);

        jLabel4.setText("Jumlah Bilangan ");
        panel.add(jLabel4);
        jLabel4.setBounds(20, 50, 100, 30);

        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(20, 80, 80, 30);

        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(20, 120, 80, 30);

        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(20, 200, 80, 30);

        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(20, 160, 80, 30);

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(100, 250, 170, 40);

        tHasil.setColumns(20);
        tHasil.setRows(5);
        jScrollPane1.setViewportView(tHasil);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(50, 310, 270, 100);
        panel.add(ket);
        ket.setBounds(100, 10, 120, 30);

        jPanel2.add(panel);
        panel.setBounds(40, 90, 360, 440);
        panel.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 440, 550);

        setBounds(0, 0, 457, 589);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
      setJenis();
 
    }//GEN-LAST:event_jenisActionPerformed

    public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns="Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        } else if 
            (jenis.getSelectedItem().equals("Pengurangan")){
            jns="Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        } else if 
            (jenis.getSelectedItem().equals("Pembagian")){
            jns="Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        } else if 
            (jenis.getSelectedItem().equals("Perkalian")){
            jns="Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        } else {
            jns = null;
            panel.setVisible(false);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
       
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2) {
                hsl = a1 + a2;
                tHasil.setText(""+a1+" + "+a2+" = "+hsl);
            }
            if(jml == 3){
                 a3 = Double.parseDouble(b3.getText().toString());
        
                hsl = a1 + a2 + a3;
                tHasil.setText(""+a1+" + "+a2+" + "+a3+" = "+hsl);    
            }
            if(jml == 4){
                 a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                tHasil.setText(""+a1+" + "+a2+" + "+a3+" + "+a4+ " = "+ hsl);
            }
        }
            else if(jns.equals("Pengurangan")){
                if(jml == 2){
                    hsl = a1 - a2;
                    tHasil.setText(""+a1+" - "+a2+" = "+hsl);
                }
                if(jml==3){
                     a3 = Double.parseDouble(b3.getText().toString());
        
                    hsl = a1 - a2 - a3;
                    tHasil.setText(""+a1+" - "+a2+" - "+a3+" = "+hsl);
                }
              if(jml == 4){
                   a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
                    hsl = a1 - a2 - a3 - a4;
                    tHasil.setText(""+a1+" - "+ a2 + " - "+ a3 + " - "+ a4+" = "+hsl);
                }
            }
            else if(jns.equals("Perkalian")){
            if(jml == 2) {
                hsl = a1 * a2;
                tHasil.setText(""+a1+" * "+a2+" = "+hsl);
            }
            if(jml == 3){
                 a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 * a2 * a3;
                tHasil.setText(""+a1+" * "+a2+" * "+a3+" = "+hsl);    
            }
            if(jml == 4){
                 a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                tHasil.setText(""+a1+" * "+a2+" * "+a3+" * "+a4+ " = "+ hsl);
            }
        }
            else if(jns.equals("Pembagian")){
            if(jml == 2) {
                
                hsl = a1 / a2;
                tHasil.setText(""+a1+" : "+a2+" = "+hsl);
            }
            if(jml == 3){
                 a3 = Double.parseDouble(b3.getText().toString());
       
                hsl = a1 / a2 / a3;
                tHasil.setText(""+a1+" : "+a2+" : "+a3+" = "+hsl);    
            }
            if(jml == 4){
                 a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                tHasil.setText(""+a1+" : "+a2+" : "+a3+" : "+a4+ " = "+ hsl);
            }
        }
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmlBilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlBilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_jmlBilActionPerformed

    public void getJumlah(){
        if(jmlBil.getSelectedItem().equals("2")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            jml = 2;
        }  else if
           (jmlBil.getSelectedItem().equals("3")){
             bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3;
        }     else if
           (jmlBil.getSelectedItem().equals("4")){
             bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml = 4;
        }  else {
          
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
           b1.setVisible(false);
            b2.setVisible(false);
            bil1.setVisible(false);
            bil2.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> jmlBil;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea tHasil;
    // End of variables declaration//GEN-END:variables
}
